In [25]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [26]:
df = pd.read_csv("regression_home_prices.csv")
df.head()

   area_sqr_ft  price_lakhs  bedrooms
0        656.0         39.0         2
1       1260.0         83.2         2
2       1057.0         86.6         3
3       1259.0         59.0         2
4       1800.0        140.0         3

In [27]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   area_sqr_ft  200 non-null    float64
 1   price_lakhs  200 non-null    float64
 2   bedrooms     200 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 4.8 KB

       area_sqr_ft  price_lakhs    bedrooms
count   200.000000   200.000000  200.000000
mean   1216.505000    79.879500    2.385000
std     328.386783    19.575765    0.487816
min     656.000000    39.000000    2.000000
25%     964.750000    64.750000    2.000000
50%    1224.500000    76.000000    2.000000
75%    1429.000000    97.000000    3.000000
max    1800.000000   140.000000    3.000000

In [28]:
X = df[['area_sqr_ft', 'bedrooms']]   # Input features
y = df['price_lakhs']                 # Output (target)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [58]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [60]:
y_pred = model.predict(X_test)

r2l = r2_score(y_test,y_pred)
r2l

0.8553362627729598

In [49]:
rf_model = RandomForestRegressor(
    n_estimators=2,
    random_state=0
)

rf_model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=2, random_state=0)

In [50]:
rf_model = RandomForestRegressor(
    n_estimators=10,
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=42)

In [51]:
y_pred = rf_model.predict(X_test)

In [52]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

Mean Squared Error: 66.9445330168572
Mean Absolute Error: 6.0456021825396835
R2 Score: 0.809902737881514

In [53]:
# Example: 1500 sq.ft house with 3 bedrooms
new_house = [[2000, 5]]

predicted_price = rf_model.predict(new_house)

print("Predicted House Price (Lakhs):", predicted_price[0])

Predicted House Price (Lakhs): 117.11658730158732

C:\Users\adhit\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(